name: Fly
author: Enzoooo_
version: 1.2
api-version: 1.16
main: fr.enzoooo.fly.Main

commands:
  fly:
    description: Vous permet de voler sans être en créatif
    permission: fly.use
  fconfig:
    description: Permet de reload la configuration du plugin sans redémarrer le serveur
    permission: fly.reload